name: ned
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.25.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.13.1+1
  cloud_firestore: ^0.13.4
  provider: ^4.0.4
  backdrop: ^0.2.8
  flutter_statusbarcolor: ^0.2.3
  fluttertoast: ^3.1.3
  charts_flutter: ^0.9.0
  url_launcher: ^5.4.2
  local_auth: ^0.6.1+3
  transparent_image: ^1.0.0
  flutter_spinkit: ^4.1.2
  image_picker: ^0.6.3+4
  image_cropper: 1.0.2
  camera: ^0.5.8+2
  path_provider: ^1.6.5
  path: ^1.6.4
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  google_sign_in: ^4.1.4
  flutter_auth_buttons: ^0.8.0
  flutter_screenutil: ^1.1.0
  validators: ^2.0.0+1
  firebase_storage: ^3.1.5
  flutter_pdfview: ^1.0.0+10
  flutter_full_pdf_viewer: ^1.0.6
  flutter_plugin_pdf_viewer: ^1.0.7
  http: ^0.12.1
  english_words: ^3.1.5
  photo_view: ^0.9.2
  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^0.3.0
  share: ^0.6.4+2
  flutter_duration_picker: ^1.0.4
  math_expressions: ^2.0.0
  slider_button: ^0.5.0
  flutter_inappwebview: ^3.4.0+2
  package_info: ^0.4.0+6
  scroll_snap_list: ^0.4.1
  video_player: ^0.10.11+2
  rubber: ^0.4.0
  flutter_svg: ^0.13.0
  timezone: ^0.5.7
  jiffy: ^3.0.1
  rate_my_app: ^0.6.0+2
  introduction_screen: ^1.0.9
  flutter_open_whatsapp: ^0.1.2
  flutter_windowmanager: ^0.0.1+1
  file_picker: ^2.1.6
  pdf_viewer_plugin: ^1.1.1









dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flame_splash_screen: 0.0.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/sprite.png
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Oxanium
       fonts:
         - asset: fonts/Oxanium-Regular.ttf

     - family: CustomIcons
       fonts:
          - asset: fonts/CustomIcons.ttf



  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
